apiVersion: v1
kind: Service
metadata:
  name: bff-backoffice
  labels:
    app.kubernetes.io/name: bff-backoffice
    app.kubernetes.io/component: bff
    app.kubernetes.io/part-of: axiomnode
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: bff-backoffice
  ports:
    - port: 7011
      targetPort: 7011
      protocol: TCP
