apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: axiomnode

resources:
  - namespace.yaml
  - microservice-quizz
  - microservice-wordpass
  - microservice-users
  - api-gateway
  - bff-mobile
  - bff-backoffice
  - backoffice
