apiVersion: v1
kind: Service
metadata:
  name: ai-engine-llama
  labels:
    app.kubernetes.io/name: ai-engine-llama
    app.kubernetes.io/component: llm
    app.kubernetes.io/part-of: axiomnode
spec:
  selector:
    app.kubernetes.io/name: ai-engine-llama
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
