apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-engine-api
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: ai-engine-api
          resources:
            requests:
              cpu: "250m"
              memory: "1Gi"
            limits:
              cpu: "1000m"
              memory: "2Gi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-engine-stats
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: ai-engine-stats
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-engine-cache
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: redis
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
