apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-quizz-api
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: microservice-quizz
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-wordpass-api
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: microservice-wordpass
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-users-api
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: microservice-users
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: api-gateway
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "128Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff-mobile
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: bff-mobile
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "128Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff-backoffice
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: bff-backoffice
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "128Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backoffice
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: backoffice
          resources:
            requests:
              cpu: "25m"
              memory: "32Mi"
            limits:
              cpu: "100m"
              memory: "64Mi"
