apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../ai-engine

patches:
  - target:
      kind: Deployment
      name: ai-engine-llama
    patch: |-
      $patch: delete
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: ai-engine-llama
  - target:
      kind: Service
      name: ai-engine-llama
    patch: |-
      $patch: delete
      apiVersion: v1
      kind: Service
      metadata:
        name: ai-engine-llama
  - target:
      kind: PersistentVolumeClaim
      name: ai-engine-llama-models
    patch: |-
      $patch: delete
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: ai-engine-llama-models
